# Generated by Django 6.0.1 on 2026-02-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transaction_quantity_transaction_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddataset',
            name='file_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
