# Generated by Django 6.0.1 on 2026-02-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_shop_address_shop_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
